name: Benchmarks
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

concurrency: benchmarks

jobs:
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.6.0
      with:
        submodules: 'recursive'
    - name: Get Engine version
      run: |
        cd RobustToolbox
        git fetch --depth=1
        echo "::set-output name=out::$(git rev-parse HEAD)"
      id: engine_version
    - name: Run script on centcomm
      uses: appleboy/ssh-action@master
      with:
        host: centcomm.spacestation14.io
        username: robust-benchmark-runner
        key: ${{ secrets.CENTCOMM_ROBUST_BENCHMARK_RUNNER_KEY }}
        command_timeout: 100000m
        script: |
          echo fuck this benchmark
