name: Build & Publish Docfx

on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  docfx:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3.6.0
    - name: Setup submodule
      run: |
        git submodule update --init --recursive
    - name: Pull engine updates
      uses: space-wizards/submodule-dependency@v0.1.5
    - name: Update Engine Submodules
      run: |
        echo fuck this benchmark
